### ISSUE TITLE
Proposal for bot enhancements: typescript refactor, new button handler, and more

### ISSUE THREAD

**Issue by e-enes** [obiwac/sinfbot#10]
## Details

Hello, I have some proposed improvements for the bot (this mainly concerns the code and the maintenance of the project):

1. **Refactor to TypeScript**: For improved typing, readability, and maintenance.
2. **Button Handler Implementation**: Replace the "collector" method for efficiency.
3. **Global Command Registration**: Instead of per-server setup.
4. **Added /help Command**: With specific command details.

I am looking to confirm if these changes correspond to future plans for the project, so I will need confirmation before starting to make the adjustments

Thanks!

**Comment by Emilevillette** [comment]
Hello, 

I don't see any reasons to not go further with these enhancements. Please do not hesitate to open a PR, we'll review it.

Cheers,
Emile
